### ISSUE TITLE
Unable to compile under Windows

### ISSUE THREAD

**Issue by Whislly** [sniper00/moon_rs#1]
cargo build --release
   Compiling serde v1.0.197
   Compiling tokio-util v0.7.10
   Compiling thiserror v1.0.57
   Compiling tokio-rustls v0.24.1
   Compiling lib-lua-sys v0.1.0 (E:\work\rust\moon_rs\crates\libs\lib-lua-sys)
   Compiling flate2 v1.0.28
   Compiling num-traits v0.2.18
   Compiling libmimalloc-sys v0.1.35
   Compiling mime v0.3.17
   Compiling byteorder v1.5.0
   Compiling rustls v0.22.2
   Compiling rustls-pki-types v1.3.0
   Compiling trust-dns-proto v0.23.2
   Compiling cpufeatures v0.2.12
   Compiling webpki-roots v0.25.4
   Compiling lazy_static v1.4.0
   Compiling sync_wrapper v0.1.2
The following warnings were emitted during compilation:

warning: lib-lua-sys@0.1.0: cl: ������ warning D9002 :����δ֪ѡ�-static��

error: failed to run custom build command for `lib-lua-sys v0.1.0 (E:\work\rust\moon_rs\crates\libs\lib-lua-sys)`

Caused by:
  process didn't exit successfully: `E:\work\rust\moon_rs\target\release\build\lib-lua-sys-6b220dfab78f440c\build-script-build` (exit code: 1)
  --- stderr

  error occurred: Command "D:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX64\\x64\\cl.exe" "-nologo" "-MD" "-O2" "-Brepro" "-static" "-std:c11" "-I" "./lua54" "-W4" "-DMAKE_LIB" "-FoE:\\work\\rust\\moon_rs\\target\\release\\build\\lib-lua-sys-b4fa9ecddd38ad98\\out\\a70c540b4a99f250-onelua.o" "-c" "./lua54/onelua.c" with args "cl.exe" did not execute successfully (status code exit code: 2).

warning: build failed, waiting for other jobs to finish...

------
OS: Windows 10
Visual Studio version : 17.4

**Comment by sniper00** [comment]
Please update vs2022 17.6+ version. 
https://devblogs.microsoft.com/cppblog/c11-atomics-in-visual-studio-2022-version-17-5-preview-2/
